server:
  port: ${PORT:8080}

spring:
  application:
    name: wedspot
  config:
    import: "optional:file:.env[.properties]"
  main:
    lazy-initialization: false
  # Database configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      data-source-properties:
        prepareThreshold: 0

  jackson:
    default-property-inclusion: non_null

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  devtools:
    restart:
      enabled: true

logging:
  level:
    org.springframework.boot.autoconfigure.jdbc: WARN
    com.zaxxer.hikari: WARN
    org.hibernate: WARN






